import type { SpecFieldDoc } from './spdx23-field-docs';

/**
 * Hand-curated field documentation for OCM component descriptors,
 * paraphrased from the Open Component Model specification
 * (https://github.com/open-component-model/ocm-spec, Community
 * Specification License 1.0 — see NOTICE). The keys mirror the SPDX doc
 * lookups the detail views use, so `docsFor()` can swap the whole set by
 * document model; fields without an OCM equivalent are simply absent.
 */

const SPEC = 'https://github.com/open-component-model/ocm-spec/blob/main/doc/01-model';
const TOPLEVEL = `${SPEC}/02-elements-toplevel.md`;
const SUB = `${SPEC}/03-elements-sub.md`;

export interface OcmFieldDoc extends SpecFieldDoc {
  /** Rendered in the ⓘ tooltip: "Open this field in the OCM specification". */
  specName: 'OCM';
}

const doc = (description: string, specUrl: string): OcmFieldDoc => ({
  description,
  specUrl,
  specName: 'OCM',
});

export const OCM_DOCS: {
  document: Record<string, OcmFieldDoc>;
  package: Record<string, OcmFieldDoc>;
  file: Record<string, OcmFieldDoc>;
  relationshipType: OcmFieldDoc;
} = {
  document: {
    documentNamespace: doc(
      'Synthetic namespace derived from the component identity (ocm://<name>/<version>). Two loaded descriptors referencing each other link up through it.',
      `${TOPLEVEL}#components`,
    ),
    spdxVersion: doc(
      'The component-descriptor schema version (meta.schemaVersion for v2; apiVersion for v3alpha1).',
      `${TOPLEVEL}#component-descriptor`,
    ),
    created: doc(
      'Creation time of the component version (component.creationTime or the ocm.software/creationTime label).',
      `${TOPLEVEL}#component-versions`,
    ),
    creators: doc(
      'The provider (organization) responsible for this component version.',
      `${TOPLEVEL}#component-versions`,
    ),
    comment: doc(
      'Descriptor summary synthesized by the viewer — schema version of the mapped component descriptor.',
      `${TOPLEVEL}#component-descriptor`,
    ),
    externalDocumentRefs: doc(
      'componentReferences: other component versions this one aggregates, addressed by component name and version.',
      `${SUB}#references`,
    ),
  },
  package: {
    versionInfo: doc(
      'Version of the component or artifact. Together with the name (and optional extraIdentity) it forms the element identity.',
      `${SUB}#identifiers`,
    ),
    primaryPackagePurpose: doc(
      'The artifact type, verbatim from the descriptor (ociImage, helmChart, sbom, blob, …) — an open set defined by the OCM type registry.',
      `${SUB}#artifact-types`,
    ),
    supplier: doc(
      'Attributed to the component provider for artifacts with relation "local" (built with the component itself).',
      `${TOPLEVEL}#component-versions`,
    ),
    downloadLocation: doc(
      'Location derived from the access specification (imageReference, url, or the localBlob reference inside a delivery).',
      `${SUB}#artifact-access`,
    ),
    SPDXID: doc(
      'Synthetic element id generated by the viewer from the artifact role and name — component descriptors have no SPDXIDs of their own.',
      `${SUB}#identifiers`,
    ),
    checksums: doc(
      'The digest value of the artifact digest triple (hashAlgorithm · normalisationAlgorithm · value), normalized for display.',
      `${SUB}#digest-info`,
    ),
    externalRefs: doc(
      'Best-effort pkg:oci package URL derived from the access imageReference — a dedupe key for inventory and conflicts, not part of the descriptor.',
      `${SUB}#artifact-access`,
    ),
  },
  file: {},
  relationshipType: doc(
    'Relationships are derived by the viewer: DESCRIBES for the component root, CONTAINS for artifacts and references, DESCRIBED_BY for SBOMs stored in the delivery.',
    `${SUB}#artifacts`,
  ),
};
