/**
 * GENERATED by scripts/extract-spec-docs.mjs — do not edit by hand.
 *
 * Field documentation distilled from the official SPDX 2.3 JSON schema
 * (https://github.com/spdx/spdx-spec, v2.3), licensed CC-BY-3.0 by the
 * SPDX project / The Linux Foundation.
 */
export interface SpecFieldDoc {
  description: string;
  enum?: readonly string[];
  /** Deep link into the rendered spec at spdx.github.io. */
  specUrl?: string;
}

export const SPDX23_DOCS: {
  document: Record<string, SpecFieldDoc>;
  package: Record<string, SpecFieldDoc>;
  file: Record<string, SpecFieldDoc>;
  relationshipType?: SpecFieldDoc;
} = {
  "document": {
    "spdxVersion": {
      "description": "Provide a reference number that can be used to understand how to parse and interpret the rest of the file. It will enable both future changes to the specification and to support backward compatibility. The version number consists of a major and minor version indicator. The major field will be incremented when incompatible changes between versions are made (one or more sections are created, modified or deleted). The minor field will be incremented when backwards compatible changes are made.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#61-spdx-version-field"
    },
    "dataLicense": {
      "description": "License expression for dataLicense. See SPDX Annex D for the license expression syntax. Compliance with the SPDX specification includes populating the SPDX fields therein with data related to such fields (\"SPDX-Metadata\"). The SPDX specification contains numerous fields where an SPDX document creator may provide relevant explanatory text in SPDX-Metadata. Without opining on the lawfulness of \"database rights\" (in jurisdictions where applicable), such explanatory text is copyrightable subject matter in most Berne Convention countries. By using the SPDX specification, or any portion hereof, you hereby agree that any copyright rights (as determined by your jurisdiction) in any SPDX-Metadata, including without limitation explanatory text, shall be subject to the terms of the Creative Commons CC0 1.0 Universal license. For SPDX-Metadata not containing any copyright rights, you hereby agree and acknowledge that the SPDX-Metadata is provided to you \"as-is\" and without any representations or warranties of any kind concerning the SPDX-Metadata, express, implied, statutory or otherwise, including without limitation warranties of title, merchantability, fitness for a particular purpose, non-infringement, or the absence of latent or other defects, accuracy, or the presence or absence of errors, whether or not discoverable, all to the greatest extent permissible under applicable law.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#62-data-license-field"
    },
    "SPDXID": {
      "description": "Uniquely identify any element in an SPDX document which may be referenced by other elements.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#63-spdx-identifier-field"
    },
    "name": {
      "description": "Identify name of this SpdxElement.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#64-document-name-field"
    },
    "documentNamespace": {
      "description": "The URI provides an unambiguous mechanism for other SPDX documents to reference SPDX elements within this SPDX document.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#65-spdx-document-namespace-field"
    },
    "documentDescribes": {
      "description": "Packages, files and/or Snippets described by this SPDX document",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/document-creation-information/"
    },
    "externalDocumentRefs": {
      "description": "Identify any external SPDX documents referenced within this SPDX document.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#66-external-document-references-field"
    },
    "created": {
      "description": "Identify when the SPDX document was originally created. The date is to be specified according to combined date and time in UTC format as specified in ISO 8601 standard.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#69-created-field"
    },
    "creators": {
      "description": "Identify who (or what, in the case of a tool) created the SPDX document. If the SPDX document was created by an individual, indicate the person's name. If the SPDX document was created on behalf of a company or organization, indicate the entity name. If the SPDX document was created using a software tool, indicate the name and version for that tool. If multiple participants or tools were involved, use multiple instances of this field. Person name or organization name may be designated as “anonymous” if appropriate.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#68-creator-field"
    }
  },
  "package": {
    "name": {
      "description": "Identify name of this SpdxElement.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#71-package-name-field"
    },
    "SPDXID": {
      "description": "Uniquely identify any element in an SPDX document which may be referenced by other elements.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#72-package-spdx-identifier-field"
    },
    "versionInfo": {
      "description": "Provides an indication of the version of the package that is described by this SpdxDocument.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#73-package-version-field"
    },
    "supplier": {
      "description": "The name and, optionally, contact information of the person or organization who was the immediate supplier of this package to the recipient. The supplier may be different than originator when the software has been repackaged. Values of this property must conform to the agent and tool syntax.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#75-package-supplier-field"
    },
    "originator": {
      "description": "The name and, optionally, contact information of the person or organization that originally created the package. Values of this property must conform to the agent and tool syntax.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#76-package-originator-field"
    },
    "downloadLocation": {
      "description": "The URI at which this package is available for download. Private (i.e., not publicly reachable) URIs are acceptable as values of this property. The values http://spdx.org/rdf/terms#none and http://spdx.org/rdf/terms#noassertion may be used to specify that the package is not downloadable or that no attempt was made to determine its download location, respectively.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#77-package-download-location-field"
    },
    "licenseConcluded": {
      "description": "License expression for licenseConcluded. See SPDX Annex D for the license expression syntax. The licensing that the preparer of this SPDX document has concluded, based on the evidence, actually applies to the SPDX Item. If the licenseConcluded field is not present for an SPDX Item, it implies an equivalent meaning to NOASSERTION.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#713-concluded-license-field"
    },
    "licenseDeclared": {
      "description": "License expression for licenseDeclared. See SPDX Annex D for the license expression syntax. The licensing that the creators of the software in the package, or the packager, have declared. Declarations by the original software creator should be preferred, if they exist.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#715-declared-license-field"
    },
    "copyrightText": {
      "description": "The text of copyright declarations recited in the package, file or snippet. If the copyrightText field is not present, it implies an equivalent meaning to NOASSERTION.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#717-copyright-text-field"
    },
    "primaryPackagePurpose": {
      "description": "This field provides information about the primary purpose of the identified package. Package Purpose is intrinsic to how the package is being used rather than the content of the package.",
      "enum": [
        "OTHER",
        "INSTALL",
        "ARCHIVE",
        "FIRMWARE",
        "APPLICATION",
        "FRAMEWORK",
        "LIBRARY",
        "CONTAINER",
        "SOURCE",
        "DEVICE",
        "OPERATING_SYSTEM",
        "FILE"
      ],
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#724-primary-package-purpose-field"
    },
    "description": {
      "description": "Provides a detailed description of the package.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#719-package-detailed-description-field"
    },
    "checksums": {
      "description": "The checksum property provides a mechanism that can be used to verify that the contents of a File or Package have not changed.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#710-package-checksum-field"
    },
    "externalRefs": {
      "description": "An External Reference allows a Package to reference an external source of additional information, metadata, enumerations, asset identifiers, or downloadable content believed to be relevant to the Package.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/package-information/#721-external-reference-field"
    }
  },
  "file": {
    "fileName": {
      "description": "The name of the file relative to the root of the package.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/file-information/#81-file-name-field"
    },
    "checksums": {
      "description": "The checksum property provides a mechanism that can be used to verify that the contents of a File or Package have not changed.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/file-information/#84-file-checksum-field"
    },
    "licenseConcluded": {
      "description": "License expression for licenseConcluded. See SPDX Annex D for the license expression syntax. The licensing that the preparer of this SPDX document has concluded, based on the evidence, actually applies to the SPDX Item. If the licenseConcluded field is not present for an SPDX Item, it implies an equivalent meaning to NOASSERTION.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/file-information/#85-concluded-license-field"
    },
    "copyrightText": {
      "description": "The text of copyright declarations recited in the package, file or snippet. If the copyrightText field is not present, it implies an equivalent meaning to NOASSERTION.",
      "specUrl": "https://spdx.github.io/spdx-spec/v2.3/file-information/#88-copyright-text-field"
    }
  },
  "relationshipType": {
    "description": "Describes the type of relationship between two SPDX elements.",
    "enum": [
      "VARIANT_OF",
      "COPY_OF",
      "PATCH_FOR",
      "TEST_DEPENDENCY_OF",
      "CONTAINED_BY",
      "DATA_FILE_OF",
      "OPTIONAL_COMPONENT_OF",
      "ANCESTOR_OF",
      "GENERATES",
      "CONTAINS",
      "OPTIONAL_DEPENDENCY_OF",
      "FILE_ADDED",
      "REQUIREMENT_DESCRIPTION_FOR",
      "DEV_DEPENDENCY_OF",
      "DEPENDENCY_OF",
      "BUILD_DEPENDENCY_OF",
      "DESCRIBES",
      "PREREQUISITE_FOR",
      "HAS_PREREQUISITE",
      "PROVIDED_DEPENDENCY_OF",
      "DYNAMIC_LINK",
      "DESCRIBED_BY",
      "METAFILE_OF",
      "DEPENDENCY_MANIFEST_OF",
      "PATCH_APPLIED",
      "RUNTIME_DEPENDENCY_OF",
      "TEST_OF",
      "TEST_TOOL_OF",
      "DEPENDS_ON",
      "SPECIFICATION_FOR",
      "FILE_MODIFIED",
      "DISTRIBUTION_ARTIFACT",
      "AMENDS",
      "DOCUMENTATION_OF",
      "GENERATED_FROM",
      "STATIC_LINK",
      "OTHER",
      "BUILD_TOOL_OF",
      "TEST_CASE_OF",
      "PACKAGE_OF",
      "DESCENDANT_OF",
      "FILE_DELETED",
      "EXPANDED_FROM_ARCHIVE",
      "DEV_TOOL_OF",
      "EXAMPLE_OF"
    ],
    "specUrl": "https://spdx.github.io/spdx-spec/v2.3/relationships-between-SPDX-elements/#111-relationship-field"
  }
};
